version: "3.8"

services:
  mehedi-portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: mehedi-portfolio
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
